cargo-features = ["workspace-inheritance"]

[package]
name = "tangram_vm"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bincode = "1.3.3"
block = "0.1.6"
camino = { workspace = true }
clap = { workspace = true }
derive_more = "0.99.17"
fatfs = { workspace = true }
futures = { workspace = true }
lazy_static = { workspace = true }
local-ip-address = "0.4.6"
macaddr = { version = "1.0.1", features = ["serde"] }
serde = { workspace = true }
serde-error = "0.1.2"
serde_ini = "0.2.0"
serde_json = { workspace = true }
serde_with = "1.13.0"
sysinfo = "0.24.7"
tangram_dirs = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
toml.workspace = true
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-unwrap = "0.9.2"
ubyte = "0.10.2"
users = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
objc = {version = "0.2.7", features=["exception"] }

[target.'cfg(target_os = "linux")'.dependencies]
vsock = "0.2.6"
tokio-vsock = "0.3.2"
tracing-journald = "0.3.0"

[dev-dependencies]
tracing-test = "0.2.1"
