[package]
name = "tangram_api_client"

description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
version = { workspace = true }

[lib]
name = "tangram_api_client"
path = "lib.rs"

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }

tangram_core = { workspace = true }
