[workspace]
members = [
  "packages/buffalo"
]

[workspace.dependencies]
buffalo = { path = "packages/buffalo" }

[package]
name = "tangram"

description = "Tangram is a programmable build system and package manager that makes your builds simple, reproducible, cacheable, and distributable."
edition = "2021"
license = "MIT"
publish = false
version = "0.0.0"

[lib]
name = "tangram"
path = "src/lib.rs"

[[bin]]
name = "tg"
path = "src/main.rs"

[build-dependencies]
v8 = "0.63.0"

[dev-dependencies]
once_cell = "1.17.1"
pretty_assertions = "1.3.0"
proptest = "1.1.0"
tempfile = "3.4.0"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
async-recursion = "1"
blake3 = "1"
buffalo = { workspace = true }
byteorder = "1.4.3"
bytes = "=1.2.1"
bzip2 = "0.4.4"
clap = { version = "4", features = ["derive"] }
deno_ast = { version = "0.24.0", features = ["transpiling"] }
derive_more = "0.99.17"
either = "1"
filetime = "0.2"
flate2 = "1"
fnv = "1"
futures = "0.3"
hex = { version = "0.4", features = ["serde"] }
http = "0.2"
hyper = { version = "0.14.24", features = ["full"] }
include_dir = "0.7"
indoc = "2"
insta = "1.28"
itertools = "0.10"
libc = "0.2"
lmdb-rkv = "0.14"
lsp-types = "0.94.0"
lz4_flex = "0.10"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
pathdiff = "0.2"
rand = "0.8"
reqwest = { version = "0.11", default-features = false, features = ["json", "stream", "rustls-tls"] }
serde = { version = "1", features = ["rc", "derive"] }
serde_json = "1"
serde_v8 = "0.84.0"
sha2 = "0.10.6"
sourcemap = "6"
tar = "0.4"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["fs"] }
tokio-util = { version = "0.7", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
url = "2"
v8 = "0.63.0"
webbrowser = "0.8"
xz = "0.1"
zip = { version = "0.6", default-features = false, features = ["aes-crypto", "deflate", "bzip2", "time"] }
zstd = "0.12.3"

[profile.release]
lto = true
strip = true

[profile.dev.package.blake3]
opt-level = 3

[profile.dev.package.bzip2]
opt-level = 3

[profile.dev.package.digest]
opt-level = 3

[profile.dev.package.flate2]
opt-level = 3

[profile.dev.package.lz4_flex]
opt-level = 3

[profile.dev.package.sha2]
opt-level = 3

[profile.dev.package.tar]
opt-level = 3

[profile.dev.package.xz]
opt-level = 3
