[workspace]
members = [
  "packages/buffalo"
]

[workspace.dependencies]
buffalo = { path = "packages/buffalo" }

[package]
name = "tangram"

description = "Tangram is a programmable build system and package manager that makes your builds simple, reproducible, cacheable, and distributable."
edition = "2021"
license = "MIT"
publish = false
version = "0.0.0"

[lib]
name = "tangram"
path = "src/lib.rs"

[[bin]]
name = "tg"
path = "src/cli/main.rs"
required-features = ["full"]

[build-dependencies]
v8 = "0.66.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
proptest = "1.1.0"
tempfile = "3.5.0"

[dependencies]
async-compression = { version = "0.4", features = ["tokio", "zstd"] }
async-recursion = "1"
base64 = "0.21"
blake3 = "1"
buffalo = { workspace = true }
byteorder = "1.4.3"
bytes = "1"
bzip2 = "0.4.4"
clap = { version = "4", features = ["derive", "env"] }
derive_more = "0.99.17"
either = { version = "1", features = ["serde"] }
filetime = "0.2"
flate2 = "1"
fnv = "1"
futures = "0.3"
hex = { version = "0.4", features = ["serde"] }
http = "0.2"
http-body-util = "0.1.0-rc.2"
http-body = "1.0.0-rc.2"
hyper = { version = "1.0.0-rc.3", features = ["full"] }
include_dir = "0.7"
indoc = "2"
itertools = "0.10"
libc = "0.2"
lmdb-rkv = "0.14"
lsp-types = "0.94.0"
lz4_flex = "0.10"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
once_cell = "1.17.1"
pathdiff = "0.2"
pin-project = "1"
rand = "0.8"
regex = "1"
reqwest = { version = "0.11", default-features = false, features = ["json", "stream", "rustls-tls"] }
serde = { version = "1", features = ["rc", "derive"] }
serde_json = "1"
serde_yaml = "0.9"
serde_v8 = { version = "0.88.0", optional = true }
sha2 = "0.10.6"
sourcemap = "6"
swc_core = { version = "0.76.29", features = ["common", "common_sourcemap", "ecma_ast", "ecma_codegen", "ecma_parser", "ecma_parser_typescript", "ecma_transforms", "ecma_transforms_module", "ecma_transforms_typescript", "ecma_visit"] }
tar = "0.4"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["fs"] }
tokio-util = { version = "0.7", features = ["full"] }
toml = "0.7"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
url = "2"
v8 = { version = "0.66.0", optional = true }
webbrowser = "0.8"
xattr = "1"
xz = "0.1"
zip = { version = "0.6", default-features = false, features = ["aes-crypto", "deflate", "bzip2", "time"] }
zstd = "0.12.3"

[features]
default = ["full"]
v8 = ["dep:v8", "dep:serde_v8"]
run = ["v8"]
full = ["v8", "run"]

[profile.dev.package.blake3]
opt-level = 3

[profile.dev.package.bzip2]
opt-level = 3

[profile.dev.package.digest]
opt-level = 3

[profile.dev.package.flate2]
opt-level = 3

[profile.dev.package.lz4_flex]
opt-level = 3

[profile.dev.package.sha2]
opt-level = 3

[profile.dev.package.tar]
opt-level = 3

[profile.dev.package.xz]
opt-level = 3
