[package]
name = "tangram"

edition = "2021"
license = "MIT"
publish = false
version = "0.0.0"

exclude = ["test"]

[lib]
name = "tangram"
path = "src/lib.rs"

[[bin]]
name = "tangram"
path = "src/cli/main.rs"

[build-dependencies]
deno_core = "0.136"
tokio = { version = "1", features = ["full"] }

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
async-recursion = "1.0"
async-trait = "0.1.53"
backtrace = "0.3"
base64 = "0.13"
bincode = "1.3.3"
bytes = "1.1"
bzip2 = "0.4"
camino = { version = "1", features = ["serde1"] }
clap = { version = "3", features = ["derive"] }
deadpool-sqlite = { version = "0.5.0", features = ["rt_tokio_1", "serde"] }
deno_core = "0.136"
derive_more = "0.99"
digest = "0.10"
duct = "0.13"
fatfs = "0.3.5"
flate2 = "1.0"
futures = "0.3"
futures-util = "0.3"
hex = { version = "0.4", features = ["serde"] }
http = "0.2"
http-serde = "1.1"
hyper = { version = "0.14.18", features = ["full"] }
hyper-rustls = "0.23"
hyperlocal = "0.8"
indexmap = "1"
indoc = "1"
insta = "1.14"
itertools = "0.10"
libc = "0.2"
nix = { version = "0.24.1", default-features = false, features = ["fs", "mount", "sched"] }
oauth2 = "4.1.0"
oci-spec = "0.5"
octorust = "0.1.35"
once_cell = "1.0"
pretty_assertions = "1.2"
rand = "0.8"
rayon = "1.0"
reqwest = { version = "0.11", default-features = false, features = ["json", "stream", "rustls-tls"] }
rusqlite = { version = "0.28", features = ["bundled"] }
rust-s3 = { version = "0.31", default-features = false, features = ["tokio-rustls-tls"] }
rustyline = "10"
scopeguard = "1.1.0"
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde-error = "0.1.2"
serde_ini = "0.2.0"
serde_json = "1.0"
serde_urlencoded = "0.7.1"
serde_with = "1.13.0"
serde_yaml = "0.8"
sha2 = "0.10"
tar = "0.4"
tempfile = "3.3"
thiserror = "1.0"
time = { version = "0.3", features = ["alloc", "formatting", "parsing"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["fs"] }
tokio-test = "0.4"
tokio-util = { version = "0.7", features = ["full"] }
toml = "0.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-test = "0.2.2"
tracing-unwrap = "0.9.2"
ubyte = "0.10.2"
url = "2.2"
users = "0.11.0"
walkdir = "2.3"
webbrowser = "0.7"
xattr = "0.2"
xz = "0.1"
zip = "0.6"
zstd = "0.10"

[profile.release]
lto = true
strip = true

[profile.dev.package.bzip2]
opt-level = 3

[profile.dev.package.flate2]
opt-level = 3

[profile.dev.package.tar]
opt-level = 3

[profile.dev.package.xz]
opt-level = 3
