[workspace]
members = [
  "packages/cli",
  "packages/core",
]

[workspace.package]
description = "Tangram is a build system and package manager that makes your builds simple, reproducible, cacheable, and distributable."
edition = "2021"
license = "MIT"
publish = false
version = "0.0.0"

[workspace.dependencies]
anyhow = { version = "1", features = ["backtrace"] }
async-recursion = "1"
async-trait = "0.1.53"
blake3 = "1"
bstr = "1"
byteorder = "1.4"
bytes = "1"
bzip2 = "0.4"
camino = { version = "1", features = ["serde1"] }
cfg-if = "1"
clap = { version = "4", features = ["derive"] }
deno_ast = { version = "0.19", features = ["transpiling"] }
deno_core = "0.154"
deno_url = "0.72"
deno_web = "0.103"
deno_webidl = "0.72"
either = "1"
flate2 = "1"
fnv = "1"
futures = "0.3"
futures-util = "0.3"
hex = { version = "0.4", features = ["serde"] }
http = "0.2"
hyper = { version = "0.14.18", features = ["full"] }
hyper-rustls = "0.23"
include_dir = "0.7"
indoc = "1"
insta = "1.14"
itertools = "0.10"
libc = "0.2"
lmdb-rkv = { version = "0.14" }
lz4_flex = "0.9"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
pathdiff = "0.2"
rand = "0.8"
regex = "1"
reqwest = { version = "0.11", default-features = false, features = ["json", "stream", "rustls-tls"] }
rustyline = "10"
serde = { version = "1", features = ["rc", "derive"] }
serde_json = "1"
serde_urlencoded = "0.7.1"
sha2 = "0.10.6"
tar = "0.4"
thiserror = "1"
time = { version = "0.3", features = ["alloc", "formatting", "parsing"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["fs"] }
tokio-util = { version = "0.7", features = ["full"] }
toml = "0.5"
tower-lsp = "0.17"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
url = "2.2"
webbrowser = "0.8"
xz = "0.1"
zip = { version = "0.6", default-features = false, features = ["aes-crypto", "deflate", "bzip2", "time"] }
zstd = "0.11"

buffalo = { git = "https://github.com/tangramdotdev/buffalo", features = ["camino"] }
tangram_cli = { path = "packages/cli" }
tangram_core = { path = "packages/core" }

[profile.release]
lto = true

[profile.dev.package.blake3]
opt-level = 3

[profile.dev.package.bzip2]
opt-level = 3

[profile.dev.package.digest]
opt-level = 3

[profile.dev.package.flate2]
opt-level = 3

[profile.dev.package.lz4_flex]
opt-level = 3

[profile.dev.package.sha2]
opt-level = 3

[profile.dev.package.tar]
opt-level = 3

[profile.dev.package.xz]
opt-level = 3
