[workspace]
members = [
  "packages/serialize"
]

[workspace.package]
authors = ["Tangram <root@tangram.dev"]
description = "Tangram is a programmable build system and package manager that makes your builds simple, reproducible, cacheable, and distributable."
edition = "2021"
homepage = "https://github.com/tangramdotdev/tangram"
license = "MIT"
repository = "https://github.com/tangramdotdev/tangram"
version = "0.0.0"

[workspace.dependencies]
tangram_serialize = { path = "packages/serialize" }

[package]
name = "tangram"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
name = "tangram"
path = "src/lib.rs"

[[bin]]
name = "tg"
path = "src/cli/main.rs"

[build-dependencies]
v8 = "=0.73.0"

[dev-dependencies]
pretty_assertions = "1"
proptest = "1"
tempfile = "3"

[dependencies]
async-compression = { version = "0.4", features = ["tokio", "zstd"] }
async-recursion = "1"
base64 = "0.21"
blake3 = "1"
tangram_serialize = { workspace = true }
byteorder = "1.4"
bytes = "1"
bzip2 = "0.4"
clap = { version = "4", features = ["derive", "env"] }
derive_more = "0.99"
either = { version = "1", features = ["serde"] }
filetime = "0.2"
flate2 = { version = "1", optional = true }
fnv = "1"
futures = "0.3"
hex = { version = "0.4", features = ["serde"] }
http = "0.2"
http-body = { version = "1.0.0-rc.2", optional = true }
http-body-util = { version = "0.1.0-rc.2", optional = true }
hyper = { version = "1.0.0-rc.3", features = ["full"], optional = true }
include_dir = "0.7"
indoc = "2"
itertools = "0.10"
libc = "0.2"
lmdb-rkv = "0.14"
lsp-types = "0.94.0"
memchr = "2"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
once_cell = "1"
pathdiff = "0.2"
pin-project = "1"
rand = "0.8"
regex = "1"
reqwest = { version = "0.11", default-features = false, features = ["json", "stream", "rustls-tls"] }
serde = { version = "1", features = ["rc", "derive"] }
serde_json = "1"
serde_v8 = { version = "=0.102.0", optional = true }
serde_yaml = "0.9"
sha2 = "0.10"
sourcemap = "6"
swc_core = { version = "=0.78.19", features = ["common", "common_sourcemap", "ecma_ast", "ecma_codegen", "ecma_parser", "ecma_parser_typescript", "ecma_transforms", "ecma_transforms_module", "ecma_transforms_typescript", "ecma_visit"] }
tar = { version = "0.4", optional = true }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["fs"] }
tokio-util = { version = "0.7", features = ["full"] }
toml = "0.7"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
url = "2"
v8 = { version = "=0.73.0", optional = true }
webbrowser = "0.8"
xattr = "1"
xz2 = { version = "0.1", optional = true }
zerocopy = "0.6"
zip = { version = "0.6", default-features = false, features = ["aes-crypto", "deflate", "bzip2", "time"] }
zstd = { version = "0.12", optional = true }

[features]
default = ["operation_run", "server"]
operation_run = ["dep:flate2", "dep:tar", "dep:xz2", "dep:zstd", "language"]
language = ["v8"]
server = ["dep:http-body", "dep:http-body-util", "dep:hyper"]
v8 = ["dep:v8", "dep:serde_v8"]

[profile.dev.package.blake3]
opt-level = 3

[profile.dev.package.bzip2]
opt-level = 3

[profile.dev.package.digest]
opt-level = 3

[profile.dev.package.flate2]
opt-level = 3

[profile.dev.package.sha2]
opt-level = 3

[profile.dev.package.tar]
opt-level = 3

[profile.dev.package.xz2]
opt-level = 3
