[package]
name = "tangram_package"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[dependencies]
async-trait = { workspace = true }
fnv = { workspace = true }
tangram_client = { workspace = true }
tangram_lsp = { workspace = true }
tokio = { workspace = true }
