[package]
name = "tangram_package"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[dependencies]
async-recursion = { workspace = true }
async-trait = { workspace = true }
fnv = { workspace = true }
im = { workspace = true }
serde = { workspace = true }
tangram_client = { workspace = true }
tangram_error = { workspace = true }
tangram_lsp = { workspace = true }
tokio = { workspace = true }
semver = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
bytes = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
tangram_http = { workspace = true }
tracing-subscriber = { workspace = true }
