[package]
name = "tangram_serialize"

authors = { workspace = true }
description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[features]
default = ["bytes", "url"]

[dependencies]
byteorder = { workspace = true }
bytes = { workspace = true, optional = true }
num = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
tangram_serialize_macro = { path = "macro" }
url = { workspace = true, optional = true }
