[package]
name = "tangram_serialize"

authors = { workspace = true }
description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[features]
default = ["url"]

[dependencies]
tangram_serialize_macro = { path = "macro" }
byteorder = "1"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
url = { version = "2", optional = true }
