# Debian linux

kernel = "./Image"
kernel_command_line = "console=hvc0 root=/dev/vda1"
boot_disk_image = "./debian-12-generic-arm64-daily-20220513-1014.raw"
guest_agent = "guest_agent"

[network_adapter]
kind = "nat"
mac = "36:84:04:a3:91:82"
