# Fedora

kernel = "./vmlinux"
initrd = "./initrd.img"
boot_disk_image = "./Fedora-Cloud-Base-36-1.5.aarch64.qcow2"
kernel_command_line = """\
console=hvc0 \
root=UUID=35cfd06b-8f75-480a-b473-3efff74041cf \
rootflags=subvol=root \
net.ifnames=0
"""

guest_agent = "./guest_agent"

[network_adapter]
kind = "nat"
mac = "36:84:04:a3:91:82"
