[package]
name = "tangram_vfs"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
libc = { workspace = true }
num = { workspace = true }
tangram_client = { workspace = true }
tangram_error = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
zerocopy = { workspace = true }
