[package]
name = "tangram_vfs"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[dependencies]
tangram_client = { workspace = true }
tokio = { workspace = true }
