[package]
name = "tangram_core"

description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
version = { workspace = true }

[lib]
name = "tangram_core"
path = "lib.rs"

[build-dependencies]
deno_core = { workspace = true }
deno_url = { workspace = true }
deno_web = { workspace = true }
deno_webidl = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
blake3 = { workspace = true }
bstr = { workspace = true }
byteorder = { workspace = true }
bytes = { workspace = true }
bzip2 = { workspace = true }
camino = { workspace = true }
cfg-if = { workspace = true }
deno_ast = { workspace = true }
deno_core = { workspace = true }
deno_url = { workspace = true }
deno_web = { workspace = true }
deno_webidl = { workspace = true }
either = { workspace = true }
flate2 = { workspace = true }
fnv = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
hyper-rustls = { workspace = true }
include_dir = { workspace = true }
indoc = { workspace = true }
insta = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
lmdb-rkv = { workspace = true }
lz4_flex = { workspace = true }
num = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
pathdiff = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
sha2 = { workspace = true }
strum = { workspace = true }
tar = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
toml = { workspace = true }
tower-lsp = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
webbrowser = { workspace = true }
xz = { workspace = true }
zip = { workspace = true }
zstd = { workspace = true }

buffalo = { workspace = true }
