[package]
name = "tangram_core"

description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
version = { workspace = true }

[lib]
name = "tangram_core"
path = "lib.rs"

[build-dependencies]
deno_core = { workspace = true }
tokio = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
bstr = { workspace = true }
blake3 = { workspace = true }
byteorder = { workspace = true }
bytes = { workspace = true }
bzip2 = { workspace = true }
camino = { workspace = true }
deadpool-sqlite = { workspace = true }
deno_ast = { workspace = true }
deno_core = { workspace = true }
digest = { workspace = true }
flate2 = { workspace = true }
fnv = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
hyper-rustls = { workspace = true }
indoc = { workspace = true }
insta = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
lz4_flex = { workspace = true }
pathdiff = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
strum = { workspace = true }
tar = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
webbrowser = { workspace = true }
xz = { workspace = true }
zip = { workspace = true }
zstd = { workspace = true }
