[package]
name = "buffalo"

authors = ["Tangram <root@tangram.dev"]
description = "Buffalo is a binary serialization format that gives you ultimate control."
documentation = "https://docs.rs/buffalo"
edition = "2021"
homepage = "https://github.com/tangramdotdev/tangram"
license = "MIT"
publish = true
repository = "https://github.com/tangramdotdev/tangram"
version = "0.4.1"

[lib]
path = "lib.rs"

[features]
default = ["url"]

[dependencies]
buffalo_macro = { version = "0.4", path = "macro" }
byteorder = "1"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
url = { version = "2", optional = true }
