[package]
name = "tangram_cli"

description = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
version = { workspace = true }

[lib]
name = "tangram_cli"
path = "lib.rs"

[[bin]]
name = "tg"
path = "main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
indoc = {workspace = true }
tokio = {workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
tokio-util = { workspace = true }
webbrowser = { workspace = true }

tangram_api_client = { workspace = true }
tangram_core = { workspace = true }