[package]
name = "tangram_cli"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[[bin]]
name = "tg"
path = "src/main.rs"

[dependencies]
bytes = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tangram_client = { workspace = true }
tangram_lsp = { workspace = true }
tangram_server = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
v8 = { workspace = true }
webbrowser = { workspace = true }
