cargo-features = ["workspace-inheritance"]

[package]
name = "tangram_sandbox"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
anyhow = { workspace = true }
camino = { workspace = true }
clap = { workspace = true }
derive_more = { workspace = true }
nix = { workspace = true }
scopeguard = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }

[target.'cfg(target_os="linux")'.dependencies]
unshare = "0.7.0"

[target.'cfg(target_os="macos")'.dependencies]
sandbox_init = { workspace = true }

[dev-dependencies]
clap = {workspace = true}
