[package]
name = "tangram_serialize_macro"

authors = { workspace = true }
description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
proc-macro = true

[dependencies]
heck = "0.4"
itertools = "0.10"
num = "0.4"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
